[project]
name = "flappybird"
version = "0.1.0"
description = "A flappy bird clone"
dependencies = [
    "pygame==2.5.2",
]
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta" 